### ISSUE TITLE
Firebase tweaking support.

### ISSUE THREAD

**Issue by miguelandres** [material-foundation/material-remixer-android#10]
We need to connect to the firebase apps. This implies integrating with both firebase and the app in  material-foundation/material-remixer-dashboard.

**Comment by wingu-wiktor** [comment]
Hi @miguelandres, 
When web dashboard for changing values can be expected?

**Comment by miguelandres** [comment]
Hi @wingu-wiktor we have a prototype but we're still designing the final version, it'll take a bit :) I'll share more when we have a better timeline.

Thanks for the interested. If you're curious subscribe to this issue and I'll be sure to update it when there is something relevant.

**Comment by miguelandres** [comment]
Closing this, while it is still being documented, the firebase remote dashboard can be found in https://github.com/material-foundation/material-remixer-remote-web and is usable already with the Android Framework using `com.google.android.libraries.remixer.storage.FirebaseRemoteControllerSyncer` as a SynchronizationMechanism
