### ISSUE TITLE
Changing the Gradle dependencies versions in the documentation 

### ISSUE THREAD

**Issue by hamz250** [material-foundation/material-remixer-android#150]
Hi guys, Thank you for the quality of work ! it seems to be really interesting.
 But would you please change the  Gradle dependencies versions in the documentation because it might cause problems with the new features (like RemixerFragment.newInstance().attachToFab)  for someone that does't pay attention to : 
dependencies {
    compile 'com.github.material-foundation.material-remixer-android:remixer:0.6.6'
    provided 'com.github.material-foundation.material-remixer-android:remixer_annotation:0.6.6'
}
Thanks,

**Comment by miguelandres** [comment]
Thanks for catching this, @hamz250. Should be fixed now, let me know.
