### ISSUE TITLE
Logo is low resolution

### ISSUE THREAD

**Issue by appsforartists** [material-foundation/material-remixer-android#41]
It looks like GitHub supports SVGs:

![](https://storage.googleapis.com/icons.google.com.a.appspot.com/google-assets/branding/product_logos/_quantum/res-export/logo_remixer_48px_clr.svg)

Can you update the logo in the README to use one?  The current one looks awful on high-res screens.

See also https://github.com/material-foundation/material-remixer-ios/issues/61

**Comment by miguelandres** [comment]
#42 fixed this
