### ISSUE TITLE
Are you affiliated with Google?

### ISSUE THREAD

**Issue by ZacSweers** [material-foundation/material-remixer-android#47]

**Comment by chriscox** [comment]
Hi Zac,

Thanks for your concern. But you can rest assured that this Material Foundation organization is actually one of Google's new homes for tools and frameworks related to our Material Design system. For more information, please check out our blog post here [Design is Never Done](https://design.google.com/articles/design-is-never-done/), as well as our new site [material.io](https://material.io) to learn how Remixer relates to the ecosystem.

Cheers!
Chris

**Comment by ZacSweers** [comment]
Thanks for the clarification! I'd recommend making that connection clearer in the README.

**Comment by miguelandres** [comment]
#48 makes the affiliation clearer.

Thanks for bringing the confusing messaging to our attention, @hzsweers

**Comment by ZacSweers** [comment]
Perfect!
