### ISSUE TITLE
[README] Dependency should be an explicit version instead of `develop-SNAPSHOT`

### ISSUE THREAD

**Issue by pingpongboss** [material-foundation/material-remixer-android#61]
Since you already have a `0.5.0` release, you should be telling clients to depend on 
```
compile 'com.github.material-foundation:material-remixer-android:0.5.0'
provided 'com.github.material-foundation.material-remixer-android:remixer_annotation:0.5.0'
```
even on `develop`.

I used to give more versioning guidance in my README (dynamic versions, etc) but decided to [take that out](https://github.com/material-motion/material-motion-runtime-android/commit/971dedd54044244f1e52051cfe57040238a82004) in favor of conciseness.

**Comment by miguelandres** [comment]
Not right now, since 0.5.0 does not have the jitpack support yet, when I cut a release I'll update this.

**Comment by miguelandres** [comment]
Keeping it open for tracking once that version is cut
