### ISSUE TITLE
RemixerFragment.attachToGesture() is easily and accidentally overwritten by client

### ISSUE THREAD

**Issue by pingpongboss** [material-foundation/material-remixer-android#62]
I called 
```
RemixerFragment remixerFragment = RemixerFragment.newInstance();
remixerFragment.attachToGesture(this, Direction.UP, 3);
```
but I was not able to call up the RemixerFragment with a 3 finger gesture. I found out that my Activity was actually calling `findViewById(android.R.id.content).setOnTouchListener()` which overwrites the GestureListener set by RemixerFragment.

It doesn't seem crazy that clients will set a touch listener on `android.R.id.content`.

I'm not sure if there's a good fix for this. This seems low priority. Maybe one way to fix this is to add a GestureView to `android.R.id.content` and set the touch listener on the GestureView.

**Comment by miguelandres** [comment]
it is documented though https://github.com/material-foundation/material-remixer-android/blob/develop/remixer_ui/src/main/java/com/google/android/libraries/remixer/ui/view/RemixerFragment.java#L86

We could wrap around the other listener if it previously exists, but it's hard to accomodate for someone else overwriting it.

**Comment by pingpongboss** [comment]
True - I do not see an easy fix. Only filed this since it stumped me for a while when I was integrating remixer.

**Comment by miguelandres** [comment]
I think I'll close this as WAI / Infeasible. Will consider reopening further down the line if it becomes an issue for users.
