### ISSUE TITLE
Rename parentObject to context?

### ISSUE THREAD

**Issue by pingpongboss** [material-foundation/material-remixer-android#68]
I just realized that `context` is a great descriptor for the current `parentObject`.

# Advantages 
- When a variable's context no longer exists, that variable should be cleaned up. 
- You can ask a variable for its context, and it will give you the activity it was created in.
- You already use "context" to explain local sync. This new usage of context aligns with that.

# Disadvantages
- Context (capital C) is a class in Android. May cause confusion.

I don't really see the disadvantage being that bad. Since the context *is* a Context, just not typed  that way for technical reasons.

**Comment by miguelandres** [comment]
Agreed. Love it, will do it soon.

**Comment by miguelandres** [comment]
I was already calling it context informally.
